import type { Branch } from '../-types/branch';

export const branches: Branch[] = [
	{
		id: '1',
		name: 'main',
		status: 'current',
		health: null,
		lastUpdated: '8m',
		ahead: 2,
		behind: 0,
		upstream: 'origin/main',
		lastCommitHash: 'c81f3a2',
		worktreePath: '/home/guilherme/repositories/anvero-api',
	},
	{
		id: '2',
		name: 'feat/auth-flow',
		status: 'worktree',
		health: 'clean',
		lastUpdated: '2h',
		ahead: 0,
		behind: 0,
		upstream: 'origin/feat/auth-flow',
		lastCommitHash: '8d4aa91',
		worktreePath: '/home/guilherme/repositories/anvero-auth',
	},
	{
		id: '3',
		name: 'fix/ssh-agent',
		status: 'worktree',
		health: 'behind',
		lastUpdated: '1d',
		ahead: 0,
		behind: 1,
		upstream: 'origin/fix/ssh-agent',
		lastCommitHash: '0fd73bc',
		worktreePath: '/home/guilherme/repositories/anvero-ssh',
	},
	{
		id: '4',
		name: 'chore/ubuntu-bootstrap',
		status: 'merged',
		health: null,
		lastUpdated: '2d',
		ahead: 0,
		behind: 0,
		upstream: 'origin/chore/ubuntu-bootstrap',
		lastCommitHash: 'a912bc4',
		worktreePath: null,
	},
	{
		id: '5',
		name: 'experiment/libgit2',
		status: 'stale',
		health: null,
		lastUpdated: '8d',
		ahead: 0,
		behind: 0,
		upstream: null,
		lastCommitHash: '45ad221',
		worktreePath: null,
	},
];
